publish_to: none
name: domain
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  injectable: ^2.1.1
  get_it: ^7.6.0

  remote:
    path: ../remote
  shared:
    path: ../shared
  data:
    path: ../data

  freezed: ^2.1.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.5

  # Auto generate some files
  build_runner: ^2.3.3

  json_serializable: ^6.7.0


flutter:

  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.domain
    iosBundleIdentifier: com.example.domain
