/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData beach_access = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_hotel = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_shopping_cart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessible = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airplanemode_active = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airport_shuttle = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audiotrack = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_center = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content_paste = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_mail = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_bike = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_bus = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_car = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_railway = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_run = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight_land = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight_takeoff = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness_center = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData free_breakfast = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headset = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_dining = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_drink = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_gas_station = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_hospital = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_pizza = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_printshop = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_shipping = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_taxi = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_answer = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_grocery_store = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance_wallet = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
